# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 03:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outros', '0002_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField()),
                ('data', models.DateTimeField(default=datetime.datetime(2017, 7, 11, 23, 41, 56, 248106))),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.Estado')),
                ('item', models.ManyToManyField(to='outros.Produto')),
            ],
        ),
    ]
