# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0003_auto_20170712_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='pedido',
        ),
        migrations.DeleteModel(
            name='Comanda',
        ),
    ]
