# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default='0,00', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='item',
            field=models.ManyToManyField(to='pedidos.Item'),
        ),
    ]
